# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bs_even_C <- function(ind_val, nbasis) {
    .Call(`_finmodtk_bs_eval`, ind_val, nbasis)
}

